name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install Dependencies
        run: |
          make create_dev_env

      - name: Run Tests
        run: |
          make tests

      - name : Run Linter
        run: |
          make lint
